# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Joint distribution of order statistics for the one- or two-group case
#' 
#' Calculates, under the assumption of joint stochastic independence, the joint distribution of order statistics for the one- or two-group case.
#' 
#' Calculates, under the assumption of joint stochastic independence, the probability P(X_(1:n)<= b_1,...,X_(n:n)<= b_n)
#' where X_(i:n) denotes the i-th order statistic of the sample X_1,...,X_n and the X_k belong to two groups distributed according
#' to a cdf G_1 or G_2.
#' 
#' The implementation is based on a generalization of Noe's recursion.
#' 
#' Returns a matrix M, where M[i,j] is the above probability (for n=i-1+j-1) where (i-1) of the X_k belong to the first group
#' and (j-1) belong to the second group.
#' 
#' @param v1 Boundaries for the first group G_1(b)
#' @param v2 Boundaries for the second group G_2(b)
#' @param n1 The maximal size of the first group - Can be at most length(v1)
#' @param n2 The maximal size of the second group - Can be at most length(v2)
#' @param parallel Use parallelization to speed up the calculation?
#' @export
noe_faithful <- function(v1, v2, n1 = -1L, n2 = -1L, parallel = TRUE) {
    .Call(`_OrdStat_noe_faithful`, v1, v2, n1, n2, parallel)
}

